/**
 * Tema: 03 Registro Alumnos
 * Conceptos: Registro Alumnos
 * Autor: Emmlg
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author lopez
 */
public class RFA_AltasAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form RFA_AltasAlumnos
     */
    public RFA_AltasAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_JinternalAltasAlum = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nombre_txf_JinternAltasAlumnos = new javax.swing.JTextField();
        direccion_txf_JinterAltasAlumnos = new javax.swing.JTextField();
        telefono_txf_JinterAltasAlumnos = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Altas Alumnos");

        jLabel1.setText("Nombre");

        jLabel2.setText("Direccion");

        jLabel3.setText("Telefono");

        javax.swing.GroupLayout bg_JinternalAltasAlumLayout = new javax.swing.GroupLayout(bg_JinternalAltasAlum);
        bg_JinternalAltasAlum.setLayout(bg_JinternalAltasAlumLayout);
        bg_JinternalAltasAlumLayout.setHorizontalGroup(
            bg_JinternalAltasAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_JinternalAltasAlumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bg_JinternalAltasAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bg_JinternalAltasAlumLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Nombre_txf_JinternAltasAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bg_JinternalAltasAlumLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(direccion_txf_JinterAltasAlumnos))
                    .addGroup(bg_JinternalAltasAlumLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefono_txf_JinterAltasAlumnos)))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        bg_JinternalAltasAlumLayout.setVerticalGroup(
            bg_JinternalAltasAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_JinternalAltasAlumLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(bg_JinternalAltasAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nombre_txf_JinternAltasAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(bg_JinternalAltasAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(direccion_txf_JinterAltasAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(bg_JinternalAltasAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(telefono_txf_JinterAltasAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_JinternalAltasAlum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_JinternalAltasAlum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nombre_txf_JinternAltasAlumnos;
    private javax.swing.JPanel bg_JinternalAltasAlum;
    private javax.swing.JTextField direccion_txf_JinterAltasAlumnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField telefono_txf_JinterAltasAlumnos;
    // End of variables declaration//GEN-END:variables
}
