/**
 * Tema: 03 Registro Alumnos
 * Conceptos: Registro Alumnos
 * Autor: Emmlg
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lopez
 */
public class RGA_Menu extends javax.swing.JFrame {

    /**
     * Creates new form RGA_Menu
     */
    public RGA_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_JPDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        windows_Jmenu = new javax.swing.JMenu();
        exit_JMitem = new javax.swing.JMenuItem();
        Alumnos_JMenu = new javax.swing.JMenu();
        altas_JMitem = new javax.swing.JMenuItem();
        BajasAlum_JMitem = new javax.swing.JMenuItem();
        cambio_JMitem = new javax.swing.JMenuItem();
        limpiar_Jmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg_JPDesktop.setBackground(new java.awt.Color(204, 204, 204));
        bg_JPDesktop.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout bg_JPDesktopLayout = new javax.swing.GroupLayout(bg_JPDesktop);
        bg_JPDesktop.setLayout(bg_JPDesktopLayout);
        bg_JPDesktopLayout.setHorizontalGroup(
            bg_JPDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );
        bg_JPDesktopLayout.setVerticalGroup(
            bg_JPDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        windows_Jmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventanas.png"))); // NOI18N

        exit_JMitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerca.png"))); // NOI18N
        exit_JMitem.setText("Salir");
        windows_Jmenu.add(exit_JMitem);

        jMenuBar1.add(windows_Jmenu);

        Alumnos_JMenu.setText("Alumnos");
        Alumnos_JMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                Alumnos_JMenuMenuSelected(evt);
            }
        });

        altas_JMitem.setText("Altas Alumnos");
        altas_JMitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altas_JMitemActionPerformed(evt);
            }
        });
        Alumnos_JMenu.add(altas_JMitem);

        BajasAlum_JMitem.setText("Bajas Alumnos");
        BajasAlum_JMitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajasAlum_JMitemActionPerformed(evt);
            }
        });
        Alumnos_JMenu.add(BajasAlum_JMitem);

        cambio_JMitem.setText("Cambios");
        Alumnos_JMenu.add(cambio_JMitem);

        jMenuBar1.add(Alumnos_JMenu);

        limpiar_Jmenu.setText("Limpiar");
        limpiar_Jmenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                limpiar_JmenuMenuSelected(evt);
            }
        });
        jMenuBar1.add(limpiar_Jmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_JPDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_JPDesktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BajasAlum_JMitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajasAlum_JMitemActionPerformed
     
   // this.bg_JPDesktop.removeAll();
 //   this.bg_JPDesktop.repaint();
    //  this.setVisible(false);
    RFA_BajasAlumnos baAlum=new RFA_BajasAlumnos();
 //   bg_JPDesktop.add(baAlum);
  
      /*  try {
            baAlum.setMaximum(true);//maximiza la ventana
        } catch (PropertyVetoException ex) {
            Logger.getLogger(RGA_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    baAlum.show();*/
    //  this.setVisible(false);
    baAlum.show();
    baAlum.setVisible(true);
    }//GEN-LAST:event_BajasAlum_JMitemActionPerformed

    private void Alumnos_JMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_Alumnos_JMenuMenuSelected

        
        
    }//GEN-LAST:event_Alumnos_JMenuMenuSelected

    private void altas_JMitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altas_JMitemActionPerformed
    
        this.bg_JPDesktop.removeAll();
        this.bg_JPDesktop.repaint();
    RFA_AltasAlumnos alAlum=new RFA_AltasAlumnos();
    bg_JPDesktop.add(alAlum);
    
        try {
            alAlum.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(RGA_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    alAlum.show();
        
        
    }//GEN-LAST:event_altas_JMitemActionPerformed

    private void limpiar_JmenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_limpiar_JmenuMenuSelected

        this.bg_JPDesktop.removeAll();
        this.bg_JPDesktop.repaint();
    }//GEN-LAST:event_limpiar_JmenuMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RGA_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RGA_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RGA_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RGA_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new RGA_Menu().setVisible(true);
                RGA_Menu ventana=new RGA_Menu();
                ventana.setExtendedState(MAXIMIZED_BOTH);
                ventana.setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Alumnos_JMenu;
    private javax.swing.JMenuItem BajasAlum_JMitem;
    private javax.swing.JMenuItem altas_JMitem;
    private javax.swing.JDesktopPane bg_JPDesktop;
    private javax.swing.JMenuItem cambio_JMitem;
    private javax.swing.JMenuItem exit_JMitem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu limpiar_Jmenu;
    private javax.swing.JMenu windows_Jmenu;
    // End of variables declaration//GEN-END:variables
}
