/**
 * Tema: Punto de Venta Jesusito
 * Conceptos: src
 * Autor: Emmlg
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author lopez
 */
public class Pv_DatosPersona extends javax.swing.JInternalFrame {

    /**
     * Creates new form DatosClientes
     */
    public Pv_DatosPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgDatosPersonas_jp = new javax.swing.JPanel();
        infPersonas_jp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        in_name_txf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        in_apePaterno_txf = new javax.swing.JTextField();
        in_apeMaterno_txf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        in_email_txf = new javax.swing.JTextField();
        in_rfc_txf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        in_currp_txf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        out_genero_jcbx = new javax.swing.JComboBox<>();
        in_phone_txf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        out_tipoPers_jcbx = new javax.swing.JComboBox<>();
        in_date_datechoser = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        in_municipiotxf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        out_estado_jcbx = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        in_colonia_txf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        in_cp_txf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        in_calle_txf = new javax.swing.JTextField();
        addUser_bttn = new javax.swing.JButton();
        cancelar_bttn = new javax.swing.JButton();
        updateDatos_bttn = new javax.swing.JButton();
        lsPersonas_jp = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsPersonas_tb = new javax.swing.JTable();
        in_searchLsPersona_txf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        delete_bttn = new javax.swing.JButton();
        modificar_btnn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        out_date_lb = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        out_usuario_lb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);

        bgDatosPersonas_jp.setBackground(new java.awt.Color(255, 255, 255));

        infPersonas_jp.setBackground(new java.awt.Color(255, 255, 255));
        infPersonas_jp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37, 60, 89), 2), " Datos Personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(37, 60, 89))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(37, 60, 89));
        jLabel1.setText("Nombre");

        in_name_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_name_txf.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        in_name_txf.setForeground(new java.awt.Color(37, 60, 89));
        in_name_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_name_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 60, 89));
        jLabel2.setText("Apellido Paterno");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(37, 60, 89));
        jLabel3.setText("Apellido Materno");

        in_apePaterno_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_apePaterno_txf.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        in_apePaterno_txf.setForeground(new java.awt.Color(37, 60, 89));
        in_apePaterno_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_apePaterno_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        in_apeMaterno_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_apeMaterno_txf.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        in_apeMaterno_txf.setForeground(new java.awt.Color(37, 60, 89));
        in_apeMaterno_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_apeMaterno_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(37, 60, 89));
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(37, 60, 89));
        jLabel5.setText("Curp");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(37, 60, 89));
        jLabel6.setText("Fecha Nacimiento");

        in_email_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_email_txf.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        in_email_txf.setForeground(new java.awt.Color(37, 60, 89));
        in_email_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_email_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        in_rfc_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_rfc_txf.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        in_rfc_txf.setForeground(new java.awt.Color(37, 60, 89));
        in_rfc_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_rfc_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(37, 60, 89));
        jLabel7.setText("RFC");

        in_currp_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_currp_txf.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        in_currp_txf.setForeground(new java.awt.Color(37, 60, 89));
        in_currp_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_currp_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(37, 60, 89));
        jLabel8.setText("Genero");

        out_genero_jcbx.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        out_genero_jcbx.setForeground(new java.awt.Color(37, 60, 89));
        out_genero_jcbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccionar --", "F", "M" }));

        in_phone_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_phone_txf.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        in_phone_txf.setForeground(new java.awt.Color(37, 60, 89));
        in_phone_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_phone_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(37, 60, 89));
        jLabel14.setText("Telefono");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(37, 60, 89));
        jLabel16.setText("Tipo de Persona ");

        out_tipoPers_jcbx.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        out_tipoPers_jcbx.setForeground(new java.awt.Color(37, 60, 89));
        out_tipoPers_jcbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecionar--", "Proveedor", "Cliente", "Empleado" }));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(37, 60, 89));
        jLabel11.setText("Municipio");

        in_municipiotxf.setBackground(new java.awt.Color(37, 60, 89));
        in_municipiotxf.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        in_municipiotxf.setForeground(new java.awt.Color(37, 60, 89));
        in_municipiotxf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_municipiotxf.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(37, 60, 89));
        jLabel13.setText("Estado");

        out_estado_jcbx.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        out_estado_jcbx.setForeground(new java.awt.Color(37, 60, 89));
        out_estado_jcbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "Chiapas", "Puebla", "Merida" }));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(37, 60, 89));
        jLabel12.setText("Colonia");

        in_colonia_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_colonia_txf.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        in_colonia_txf.setForeground(new java.awt.Color(37, 60, 89));
        in_colonia_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_colonia_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(37, 60, 89));
        jLabel15.setText("C.P");

        in_cp_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_cp_txf.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        in_cp_txf.setForeground(new java.awt.Color(37, 60, 89));
        in_cp_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_cp_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(37, 60, 89));
        jLabel10.setText("Calle");

        in_calle_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_calle_txf.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        in_calle_txf.setForeground(new java.awt.Color(37, 60, 89));
        in_calle_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_calle_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        addUser_bttn.setBackground(new java.awt.Color(255, 255, 255));
        addUser_bttn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        addUser_bttn.setForeground(new java.awt.Color(37, 60, 89));
        addUser_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addUser.png"))); // NOI18N
        addUser_bttn.setText("Agregar");
        addUser_bttn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        cancelar_bttn.setBackground(new java.awt.Color(255, 255, 255));
        cancelar_bttn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        cancelar_bttn.setForeground(new java.awt.Color(37, 60, 89));
        cancelar_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        cancelar_bttn.setText("Cancelar");
        cancelar_bttn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        updateDatos_bttn.setBackground(new java.awt.Color(255, 255, 255));
        updateDatos_bttn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        updateDatos_bttn.setForeground(new java.awt.Color(37, 60, 89));
        updateDatos_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/updateUser.png"))); // NOI18N
        updateDatos_bttn.setText("Actualizar Datos");
        updateDatos_bttn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout infPersonas_jpLayout = new javax.swing.GroupLayout(infPersonas_jp);
        infPersonas_jp.setLayout(infPersonas_jpLayout);
        infPersonas_jpLayout.setHorizontalGroup(
            infPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infPersonas_jpLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(infPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addGap(570, 570, 570)
                        .addComponent(addUser_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cancelar_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(updateDatos_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(21, 21, 21)
                        .addComponent(out_tipoPers_jcbx, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6)
                        .addGap(23, 23, 23)
                        .addComponent(in_date_datechoser, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel11)
                        .addGap(26, 26, 26)
                        .addComponent(in_municipiotxf, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(in_name_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(jLabel5)
                        .addGap(22, 22, 22)
                        .addComponent(in_currp_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel13)
                        .addGap(26, 26, 26)
                        .addComponent(out_estado_jcbx, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addComponent(in_apePaterno_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel8)
                        .addGap(34, 34, 34)
                        .addComponent(out_genero_jcbx, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel12)
                        .addGap(31, 31, 31)
                        .addComponent(in_colonia_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22)
                        .addComponent(in_apeMaterno_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(jLabel7)
                        .addGap(36, 36, 36)
                        .addComponent(in_rfc_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel10)
                        .addGap(32, 32, 32)
                        .addComponent(in_calle_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(in_email_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel14)
                        .addGap(33, 33, 33)
                        .addComponent(in_phone_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel15)
                        .addGap(33, 33, 33)
                        .addComponent(in_cp_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        infPersonas_jpLayout.setVerticalGroup(
            infPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infPersonas_jpLayout.createSequentialGroup()
                .addGroup(infPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addUser_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateDatos_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(infPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(out_tipoPers_jcbx, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_date_datechoser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_municipiotxf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(infPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))))
                .addGap(18, 18, 18)
                .addGroup(infPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(in_name_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addComponent(in_currp_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel13))
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(out_estado_jcbx, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(infPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addComponent(in_apePaterno_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addComponent(out_genero_jcbx, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel12))
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(in_colonia_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(infPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addComponent(in_apeMaterno_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7))
                    .addComponent(in_rfc_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10))
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(in_calle_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(infPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(in_email_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_phone_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(in_cp_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infPersonas_jpLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(infPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        lsPersonas_jp.setBackground(new java.awt.Color(255, 255, 255));
        lsPersonas_jp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37, 60, 89), 2), "Lista de Personas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(37, 60, 89))); // NOI18N

        lsPersonas_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave de identidad", "Nombre", "Curp", "Fecha de Nac.", "Género", "RFC", "Teléfono", "Dirección"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lsPersonas_tb);
        if (lsPersonas_tb.getColumnModel().getColumnCount() > 0) {
            lsPersonas_tb.getColumnModel().getColumn(0).setMinWidth(120);
            lsPersonas_tb.getColumnModel().getColumn(1).setMinWidth(160);
            lsPersonas_tb.getColumnModel().getColumn(2).setMinWidth(180);
            lsPersonas_tb.getColumnModel().getColumn(3).setMinWidth(150);
            lsPersonas_tb.getColumnModel().getColumn(4).setMinWidth(110);
            lsPersonas_tb.getColumnModel().getColumn(4).setMaxWidth(120);
            lsPersonas_tb.getColumnModel().getColumn(5).setMinWidth(140);
            lsPersonas_tb.getColumnModel().getColumn(6).setMinWidth(120);
            lsPersonas_tb.getColumnModel().getColumn(7).setMinWidth(140);
        }

        in_searchLsPersona_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_searchLsPersona_txf.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        in_searchLsPersona_txf.setForeground(new java.awt.Color(37, 60, 89));
        in_searchLsPersona_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/research.png"))); // NOI18N

        delete_bttn.setBackground(new java.awt.Color(255, 255, 255));
        delete_bttn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        delete_bttn.setForeground(new java.awt.Color(37, 60, 89));
        delete_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelUser.png"))); // NOI18N
        delete_bttn.setText("Eliminar");
        delete_bttn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        modificar_btnn.setBackground(new java.awt.Color(255, 255, 255));
        modificar_btnn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        modificar_btnn.setForeground(new java.awt.Color(37, 60, 89));
        modificar_btnn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        modificar_btnn.setText("Modificar");
        modificar_btnn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout lsPersonas_jpLayout = new javax.swing.GroupLayout(lsPersonas_jp);
        lsPersonas_jp.setLayout(lsPersonas_jpLayout);
        lsPersonas_jpLayout.setHorizontalGroup(
            lsPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lsPersonas_jpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lsPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lsPersonas_jpLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(in_searchLsPersona_txf)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGap(71, 71, 71)
                        .addComponent(delete_bttn)
                        .addGap(27, 27, 27)
                        .addComponent(modificar_btnn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        lsPersonas_jpLayout.setVerticalGroup(
            lsPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lsPersonas_jpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lsPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lsPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(modificar_btnn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(delete_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(in_searchLsPersona_txf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(37, 60, 89));
        jLabel9.setText("Fecha ");

        out_date_lb.setBackground(new java.awt.Color(255, 255, 255));
        out_date_lb.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        out_date_lb.setForeground(new java.awt.Color(37, 60, 89));
        out_date_lb.setText("10/feb/2023");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(37, 60, 89));
        jLabel19.setText("Sesión");

        out_usuario_lb.setBackground(new java.awt.Color(255, 255, 255));
        out_usuario_lb.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        out_usuario_lb.setForeground(new java.awt.Color(37, 60, 89));
        out_usuario_lb.setText("Usuario 002");

        javax.swing.GroupLayout bgDatosPersonas_jpLayout = new javax.swing.GroupLayout(bgDatosPersonas_jp);
        bgDatosPersonas_jp.setLayout(bgDatosPersonas_jpLayout);
        bgDatosPersonas_jpLayout.setHorizontalGroup(
            bgDatosPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgDatosPersonas_jpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgDatosPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgDatosPersonas_jpLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(out_date_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(out_usuario_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lsPersonas_jp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infPersonas_jp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        bgDatosPersonas_jpLayout.setVerticalGroup(
            bgDatosPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgDatosPersonas_jpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgDatosPersonas_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(out_date_lb)
                    .addComponent(jLabel19)
                    .addComponent(out_usuario_lb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infPersonas_jp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lsPersonas_jp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        getContentPane().add(bgDatosPersonas_jp, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUser_bttn;
    private javax.swing.JPanel bgDatosPersonas_jp;
    private javax.swing.JButton cancelar_bttn;
    private javax.swing.JButton delete_bttn;
    private javax.swing.JTextField in_apeMaterno_txf;
    private javax.swing.JTextField in_apePaterno_txf;
    private javax.swing.JTextField in_calle_txf;
    private javax.swing.JTextField in_colonia_txf;
    private javax.swing.JTextField in_cp_txf;
    private javax.swing.JTextField in_currp_txf;
    private com.toedter.calendar.JDateChooser in_date_datechoser;
    private javax.swing.JTextField in_email_txf;
    private javax.swing.JTextField in_municipiotxf;
    private javax.swing.JTextField in_name_txf;
    private javax.swing.JTextField in_phone_txf;
    private javax.swing.JTextField in_rfc_txf;
    private javax.swing.JTextField in_searchLsPersona_txf;
    private javax.swing.JPanel infPersonas_jp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lsPersonas_jp;
    private javax.swing.JTable lsPersonas_tb;
    private javax.swing.JButton modificar_btnn;
    private javax.swing.JLabel out_date_lb;
    private javax.swing.JComboBox<String> out_estado_jcbx;
    private javax.swing.JComboBox<String> out_genero_jcbx;
    private javax.swing.JComboBox<String> out_tipoPers_jcbx;
    private javax.swing.JLabel out_usuario_lb;
    private javax.swing.JButton updateDatos_bttn;
    // End of variables declaration//GEN-END:variables
}
