/**
 * Tema: Punto de Venta Jesusito
 * Conceptos: src
 * Autor: Emmlg
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author lopez
 */
public class Pv_Inventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pv_Inventario
     */
    public Pv_Inventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        datosProducto_jp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        in_idProducto_txf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        in_descripcionP_txa = new javax.swing.JTextArea();
        in_stoke_txf = new javax.swing.JTextField();
        in_ubicacion_txf = new javax.swing.JTextField();
        in_marcaP_txf = new javax.swing.JTextField();
        out_proveedor_jcbx = new javax.swing.JComboBox<>();
        in_precioVenta_txf = new javax.swing.JTextField();
        in_PrecioCompra_txf = new javax.swing.JTextField();
        in_numPartes_txf = new javax.swing.JTextField();
        in_marcaCoche_txf = new javax.swing.JTextField();
        out_categoriaP_jcbx = new javax.swing.JComboBox<>();
        in_anioCoche_txf = new javax.swing.JTextField();
        in_modeloCoche_txf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        addProduct_bttn = new javax.swing.JButton();
        updateProduct_bttn = new javax.swing.JButton();
        cancelar_bttn = new javax.swing.JButton();
        lsProducto_jp = new javax.swing.JPanel();
        in_searchLsProducto_txf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        eliminar_bttn = new javax.swing.JButton();
        modificar_bttn = new javax.swing.JButton();
        reiniciarDB_bttn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsProducto_tb = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);

        datosProducto_jp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37, 60, 89), 2), "Datos del Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 20), new java.awt.Color(37, 60, 89))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(37, 60, 89));
        jLabel1.setText("Código de Barras");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 60, 89));
        jLabel2.setText("Detalles del Producto");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(37, 60, 89));
        jLabel3.setText("Stock");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(37, 60, 89));
        jLabel4.setText("Ubicación");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(37, 60, 89));
        jLabel5.setText("Marca");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(37, 60, 89));
        jLabel6.setText("Proveedor");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(37, 60, 89));
        jLabel7.setText("Precio Venta");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(37, 60, 89));
        jLabel8.setText("Precio Compra");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(37, 60, 89));
        jLabel9.setText("No. Parte");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(37, 60, 89));
        jLabel10.setText("Categoría");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(37, 60, 89));
        jLabel11.setText("Marca del Coche");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(37, 60, 89));
        jLabel12.setText("Año del Coche");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(37, 60, 89));
        jLabel13.setText("Modelo de Coche");

        in_idProducto_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_idProducto_txf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        in_idProducto_txf.setForeground(new java.awt.Color(255, 255, 255));
        in_idProducto_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_idProducto_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        in_descripcionP_txa.setBackground(new java.awt.Color(37, 60, 89));
        in_descripcionP_txa.setColumns(20);
        in_descripcionP_txa.setForeground(new java.awt.Color(255, 255, 255));
        in_descripcionP_txa.setRows(5);
        in_descripcionP_txa.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(in_descripcionP_txa);

        in_stoke_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_stoke_txf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        in_stoke_txf.setForeground(new java.awt.Color(255, 255, 255));
        in_stoke_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_stoke_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        in_ubicacion_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_ubicacion_txf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        in_ubicacion_txf.setForeground(new java.awt.Color(255, 255, 255));
        in_ubicacion_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_ubicacion_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        in_marcaP_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_marcaP_txf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        in_marcaP_txf.setForeground(new java.awt.Color(255, 255, 255));
        in_marcaP_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_marcaP_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        out_proveedor_jcbx.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        out_proveedor_jcbx.setForeground(new java.awt.Color(37, 60, 89));
        out_proveedor_jcbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        in_precioVenta_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_precioVenta_txf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        in_precioVenta_txf.setForeground(new java.awt.Color(255, 255, 255));
        in_precioVenta_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_precioVenta_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        in_PrecioCompra_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_PrecioCompra_txf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        in_PrecioCompra_txf.setForeground(new java.awt.Color(255, 255, 255));
        in_PrecioCompra_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_PrecioCompra_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        in_numPartes_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_numPartes_txf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        in_numPartes_txf.setForeground(new java.awt.Color(255, 255, 255));
        in_numPartes_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_numPartes_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        in_marcaCoche_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_marcaCoche_txf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        in_marcaCoche_txf.setForeground(new java.awt.Color(255, 255, 255));
        in_marcaCoche_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_marcaCoche_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        out_categoriaP_jcbx.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        out_categoriaP_jcbx.setForeground(new java.awt.Color(37, 60, 89));
        out_categoriaP_jcbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        in_anioCoche_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_anioCoche_txf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        in_anioCoche_txf.setForeground(new java.awt.Color(255, 255, 255));
        in_anioCoche_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_anioCoche_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        in_modeloCoche_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_modeloCoche_txf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        in_modeloCoche_txf.setForeground(new java.awt.Color(255, 255, 255));
        in_modeloCoche_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_modeloCoche_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addCategory.png"))); // NOI18N

        addProduct_bttn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        addProduct_bttn.setForeground(new java.awt.Color(37, 60, 89));
        addProduct_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addnewProduct.png"))); // NOI18N
        addProduct_bttn.setText("Agregar Producto");
        addProduct_bttn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        updateProduct_bttn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        updateProduct_bttn.setForeground(new java.awt.Color(37, 60, 89));
        updateProduct_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/updateProduct.png"))); // NOI18N
        updateProduct_bttn.setText("Actualizar Producto");
        updateProduct_bttn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        cancelar_bttn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        cancelar_bttn.setForeground(new java.awt.Color(37, 60, 89));
        cancelar_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        cancelar_bttn.setText("Cancelar");
        cancelar_bttn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout datosProducto_jpLayout = new javax.swing.GroupLayout(datosProducto_jp);
        datosProducto_jp.setLayout(datosProducto_jpLayout);
        datosProducto_jpLayout.setHorizontalGroup(
            datosProducto_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosProducto_jpLayout.createSequentialGroup()
                .addGroup(datosProducto_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addComponent(in_idProducto_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(out_proveedor_jcbx, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel11))
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(in_ubicacion_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(in_numPartes_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel13))
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(in_marcaP_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel10)
                        .addGap(27, 27, 27)
                        .addComponent(out_categoriaP_jcbx, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel15)
                        .addGap(25, 25, 25)
                        .addComponent(in_modeloCoche_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(datosProducto_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(datosProducto_jpLayout.createSequentialGroup()
                                .addComponent(addProduct_bttn)
                                .addGap(27, 27, 27)
                                .addComponent(cancelar_bttn)
                                .addGap(30, 30, 30)
                                .addComponent(updateProduct_bttn))
                            .addGroup(datosProducto_jpLayout.createSequentialGroup()
                                .addGroup(datosProducto_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(in_stoke_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(datosProducto_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(datosProducto_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(in_precioVenta_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in_PrecioCompra_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(78, 78, 78)
                                .addGroup(datosProducto_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(in_marcaCoche_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(in_anioCoche_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        datosProducto_jpLayout.setVerticalGroup(
            datosProducto_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosProducto_jpLayout.createSequentialGroup()
                .addGroup(datosProducto_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar_bttn)
                    .addComponent(updateProduct_bttn)
                    .addComponent(addProduct_bttn))
                .addGap(25, 25, 25)
                .addGroup(datosProducto_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addComponent(in_idProducto_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel6))
                    .addComponent(out_proveedor_jcbx, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel11)))
                .addGap(16, 16, 16)
                .addGroup(datosProducto_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)
                        .addComponent(in_stoke_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel8))
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(in_precioVenta_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(in_PrecioCompra_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addComponent(in_marcaCoche_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(21, 21, 21)
                        .addComponent(in_anioCoche_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(datosProducto_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addComponent(in_ubicacion_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel9))
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(in_numPartes_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel13)))
                .addGap(9, 9, 9)
                .addGroup(datosProducto_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addComponent(in_marcaP_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10))
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(out_categoriaP_jcbx, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel15))
                    .addGroup(datosProducto_jpLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(in_modeloCoche_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lsProducto_jp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37, 60, 89), 2), "Lista de Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(37, 60, 89))); // NOI18N

        in_searchLsProducto_txf.setBackground(new java.awt.Color(37, 60, 89));
        in_searchLsProducto_txf.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        in_searchLsProducto_txf.setForeground(new java.awt.Color(255, 255, 255));
        in_searchLsProducto_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        in_searchLsProducto_txf.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/research.png"))); // NOI18N

        eliminar_bttn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        eliminar_bttn.setForeground(new java.awt.Color(37, 60, 89));
        eliminar_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clean.png"))); // NOI18N
        eliminar_bttn.setText("Eliminar");
        eliminar_bttn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        modificar_bttn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        modificar_bttn.setForeground(new java.awt.Color(37, 60, 89));
        modificar_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        modificar_bttn.setText("Modificar");
        modificar_bttn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        reiniciarDB_bttn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        reiniciarDB_bttn.setForeground(new java.awt.Color(37, 60, 89));
        reiniciarDB_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/resetDB.png"))); // NOI18N
        reiniciarDB_bttn.setText("Reiniciar DB");
        reiniciarDB_bttn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lsProducto_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Barras", "Descripción", "Cantidad", "Marca", "Proveedor", "Precio Costo", "Precio Venta", "Categoría", "Marca del Coche", "Año del Coche", "Modelo del Coche"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lsProducto_tb.setRowHeight(30);
        jScrollPane2.setViewportView(lsProducto_tb);
        if (lsProducto_tb.getColumnModel().getColumnCount() > 0) {
            lsProducto_tb.getColumnModel().getColumn(0).setMinWidth(110);
            lsProducto_tb.getColumnModel().getColumn(1).setMinWidth(130);
            lsProducto_tb.getColumnModel().getColumn(2).setMinWidth(110);
            lsProducto_tb.getColumnModel().getColumn(2).setMaxWidth(110);
            lsProducto_tb.getColumnModel().getColumn(3).setMinWidth(120);
            lsProducto_tb.getColumnModel().getColumn(3).setMaxWidth(125);
            lsProducto_tb.getColumnModel().getColumn(4).setMinWidth(120);
            lsProducto_tb.getColumnModel().getColumn(5).setMinWidth(120);
            lsProducto_tb.getColumnModel().getColumn(5).setMaxWidth(130);
            lsProducto_tb.getColumnModel().getColumn(6).setMinWidth(125);
            lsProducto_tb.getColumnModel().getColumn(6).setMaxWidth(130);
            lsProducto_tb.getColumnModel().getColumn(7).setMinWidth(150);
            lsProducto_tb.getColumnModel().getColumn(7).setMaxWidth(150);
            lsProducto_tb.getColumnModel().getColumn(8).setMinWidth(150);
            lsProducto_tb.getColumnModel().getColumn(8).setMaxWidth(160);
            lsProducto_tb.getColumnModel().getColumn(9).setMinWidth(125);
            lsProducto_tb.getColumnModel().getColumn(9).setMaxWidth(130);
            lsProducto_tb.getColumnModel().getColumn(10).setMinWidth(160);
        }

        javax.swing.GroupLayout lsProducto_jpLayout = new javax.swing.GroupLayout(lsProducto_jp);
        lsProducto_jp.setLayout(lsProducto_jpLayout);
        lsProducto_jpLayout.setHorizontalGroup(
            lsProducto_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lsProducto_jpLayout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(in_searchLsProducto_txf)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(eliminar_bttn)
                .addGap(48, 48, 48)
                .addComponent(modificar_bttn)
                .addGap(39, 39, 39)
                .addComponent(reiniciarDB_bttn)
                .addGap(21, 21, 21))
            .addGroup(lsProducto_jpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        lsProducto_jpLayout.setVerticalGroup(
            lsProducto_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lsProducto_jpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lsProducto_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(in_searchLsProducto_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(lsProducto_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eliminar_bttn)
                        .addComponent(modificar_bttn)
                        .addComponent(reiniciarDB_bttn)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lsProducto_jp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(datosProducto_jp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(datosProducto_jp, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lsProducto_jp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct_bttn;
    private javax.swing.JButton cancelar_bttn;
    private javax.swing.JPanel datosProducto_jp;
    private javax.swing.JButton eliminar_bttn;
    private javax.swing.JTextField in_PrecioCompra_txf;
    private javax.swing.JTextField in_anioCoche_txf;
    private javax.swing.JTextArea in_descripcionP_txa;
    private javax.swing.JTextField in_idProducto_txf;
    private javax.swing.JTextField in_marcaCoche_txf;
    private javax.swing.JTextField in_marcaP_txf;
    private javax.swing.JTextField in_modeloCoche_txf;
    private javax.swing.JTextField in_numPartes_txf;
    private javax.swing.JTextField in_precioVenta_txf;
    private javax.swing.JTextField in_searchLsProducto_txf;
    private javax.swing.JTextField in_stoke_txf;
    private javax.swing.JTextField in_ubicacion_txf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel lsProducto_jp;
    private javax.swing.JTable lsProducto_tb;
    private javax.swing.JButton modificar_bttn;
    private javax.swing.JComboBox<String> out_categoriaP_jcbx;
    private javax.swing.JComboBox<String> out_proveedor_jcbx;
    private javax.swing.JButton reiniciarDB_bttn;
    private javax.swing.JButton updateProduct_bttn;
    // End of variables declaration//GEN-END:variables
}
