/**
 * Tema: Punto de Venta Jesusito
 * Conceptos: src
 * Autor: Emmlg
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author lopez
 */



public class Pv_Ventas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ventas
     */
    public Pv_Ventas() {
        initComponents();
        TextPrompt placeholder = new TextPrompt("Busca tu productos aquí",input_searchProduct_txf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgBlueVenta_jp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        frPago_jcbx = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        out_total_lb = new javax.swing.JLabel();
        in_efectivo_txf = new javax.swing.JTextField();
        out_pago_lb = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        descuento_jcbx = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        clientes_jcbx = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        out_cambio_lb = new javax.swing.JLabel();
        cobrar_bttn = new javax.swing.JButton();
        cancelarCobro_bttn = new javax.swing.JButton();
        out_folioVenta_lb = new javax.swing.JLabel();
        bgWhiteVenta_jp = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        input_searchProduct_txf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsProducto_tb = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsproductoV_tb = new javax.swing.JTable();
        cotizar_bttn = new javax.swing.JButton();
        vaciarlista_bttn = new javax.swing.JButton();
        quitarls_bttn = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        out_dateV_lb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        out_usuario_lb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setResizable(true);

        bgBlueVenta_jp.setBackground(new java.awt.Color(37, 60, 89));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Folio de Venta : ");

        jPanel2.setBackground(new java.awt.Color(37, 60, 89));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Cobro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 22), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Sub Total ");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Iva ");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Efectivo");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cambio");

        jCheckBox1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Factura");
        jCheckBox1.setContentAreaFilled(false);

        jCheckBox2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Ticket");
        jCheckBox2.setContentAreaFilled(false);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Forma de Pago ");

        frPago_jcbx.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        frPago_jcbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- seleccionar --", "Debito", "Credito" }));

        jLabel17.setBackground(new java.awt.Color(37, 60, 89));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("$ 430.0");
        jLabel17.setOpaque(true);

        jLabel18.setBackground(new java.awt.Color(37, 60, 89));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("16 %");
        jLabel18.setOpaque(true);

        out_total_lb.setBackground(new java.awt.Color(37, 60, 89));
        out_total_lb.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        out_total_lb.setForeground(new java.awt.Color(255, 255, 255));
        out_total_lb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        out_total_lb.setText("$ 525.0");
        out_total_lb.setOpaque(true);

        in_efectivo_txf.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        in_efectivo_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        out_pago_lb.setBackground(new java.awt.Color(37, 60, 89));
        out_pago_lb.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        out_pago_lb.setForeground(new java.awt.Color(255, 255, 255));
        out_pago_lb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        out_pago_lb.setText("$ 20.0");
        out_pago_lb.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Descuento ");

        descuento_jcbx.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        descuento_jcbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- seleccionar --", "Descuento Amigo", "Descuento especial", "Cliente frecuente" }));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cliente ");

        clientes_jcbx.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        clientes_jcbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- selecciona --", "cliente 1", "cliente 2", "cliente 3" }));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addUser.png"))); // NOI18N

        jSeparator1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pago");

        out_cambio_lb.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        out_cambio_lb.setForeground(new java.awt.Color(255, 255, 255));
        out_cambio_lb.setText("$ 42.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(27, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(198, 198, 198))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(28, 28, 28)
                                        .addComponent(clientes_jcbx, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(129, 129, 129))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(34, 34, 34))
                            .addComponent(in_efectivo_txf))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(descuento_jcbx, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(frPago_jcbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(56, 56, 56))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(87, 87, 87)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel5))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(out_pago_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(out_total_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(out_cambio_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(104, 104, 104))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientes_jcbx, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(descuento_jcbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(frPago_jcbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_efectivo_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(out_total_lb))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(out_pago_lb)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(out_cambio_lb))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox1))
                .addGap(0, 0, 0))
        );

        cobrar_bttn.setBackground(new java.awt.Color(255, 255, 255));
        cobrar_bttn.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        cobrar_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/payment.png"))); // NOI18N
        cobrar_bttn.setText("Cobrar");
        cobrar_bttn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        cancelarCobro_bttn.setBackground(new java.awt.Color(255, 255, 255));
        cancelarCobro_bttn.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        cancelarCobro_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelPayment.png"))); // NOI18N
        cancelarCobro_bttn.setText("Cancelar  Cobro");
        cancelarCobro_bttn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        out_folioVenta_lb.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        out_folioVenta_lb.setForeground(new java.awt.Color(255, 255, 255));
        out_folioVenta_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        out_folioVenta_lb.setText("Venta 001");

        javax.swing.GroupLayout bgBlueVenta_jpLayout = new javax.swing.GroupLayout(bgBlueVenta_jp);
        bgBlueVenta_jp.setLayout(bgBlueVenta_jpLayout);
        bgBlueVenta_jpLayout.setHorizontalGroup(
            bgBlueVenta_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBlueVenta_jpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgBlueVenta_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgBlueVenta_jpLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33)
                        .addComponent(out_folioVenta_lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50))
                    .addGroup(bgBlueVenta_jpLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(bgBlueVenta_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cobrar_bttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelarCobro_bttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bgBlueVenta_jpLayout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        bgBlueVenta_jpLayout.setVerticalGroup(
            bgBlueVenta_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBlueVenta_jpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgBlueVenta_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(out_folioVenta_lb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(cobrar_bttn)
                .addGap(18, 18, 18)
                .addComponent(cancelarCobro_bttn)
                .addGap(31, 31, 31))
        );

        bgWhiteVenta_jp.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37, 60, 89), 2), "Datos Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16), new java.awt.Color(37, 60, 89))); // NOI18N

        input_searchProduct_txf.setBackground(new java.awt.Color(37, 60, 89));
        input_searchProduct_txf.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        input_searchProduct_txf.setForeground(new java.awt.Color(255, 255, 255));
        input_searchProduct_txf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_searchProduct_txf.setToolTipText("");
        input_searchProduct_txf.setCaretColor(new java.awt.Color(255, 255, 255));
        input_searchProduct_txf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_searchProduct_txf.setName(""); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/research.png"))); // NOI18N

        jButton5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(37, 60, 89));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addItem.png"))); // NOI18N
        jButton5.setText("Agregar a lista");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lsProducto_tb.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lsProducto_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripción", "Cantidad", "Precio", "Marca", "Marca Coche", "Modelo coche", "Año Coche"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lsProducto_tb.setRowHeight(30);
        jScrollPane2.setViewportView(lsProducto_tb);
        if (lsProducto_tb.getColumnModel().getColumnCount() > 0) {
            lsProducto_tb.getColumnModel().getColumn(0).setMinWidth(120);
            lsProducto_tb.getColumnModel().getColumn(0).setMaxWidth(120);
            lsProducto_tb.getColumnModel().getColumn(1).setMinWidth(180);
            lsProducto_tb.getColumnModel().getColumn(2).setMinWidth(100);
            lsProducto_tb.getColumnModel().getColumn(2).setMaxWidth(100);
            lsProducto_tb.getColumnModel().getColumn(3).setMinWidth(110);
            lsProducto_tb.getColumnModel().getColumn(3).setMaxWidth(110);
            lsProducto_tb.getColumnModel().getColumn(4).setMinWidth(140);
            lsProducto_tb.getColumnModel().getColumn(5).setMinWidth(140);
            lsProducto_tb.getColumnModel().getColumn(6).setMinWidth(140);
            lsProducto_tb.getColumnModel().getColumn(7).setMinWidth(120);
            lsProducto_tb.getColumnModel().getColumn(7).setMaxWidth(120);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(input_searchProduct_txf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(120, 120, 120)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_searchProduct_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
        );

        input_searchProduct_txf.getAccessibleContext().setAccessibleName("");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37, 60, 89), 2), " Lista de Productos ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 16), new java.awt.Color(37, 60, 89))); // NOI18N

        lsproductoV_tb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lsproductoV_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripcion", "Marca", "Modelo Coche", "Precio", "Cantidad", "Sub Total"
            }
        ));
        lsproductoV_tb.setRowHeight(30);
        jScrollPane1.setViewportView(lsproductoV_tb);
        if (lsproductoV_tb.getColumnModel().getColumnCount() > 0) {
            lsproductoV_tb.getColumnModel().getColumn(0).setMinWidth(100);
            lsproductoV_tb.getColumnModel().getColumn(1).setMinWidth(160);
            lsproductoV_tb.getColumnModel().getColumn(2).setMinWidth(140);
            lsproductoV_tb.getColumnModel().getColumn(3).setMinWidth(140);
            lsproductoV_tb.getColumnModel().getColumn(4).setMinWidth(120);
            lsproductoV_tb.getColumnModel().getColumn(4).setMaxWidth(130);
            lsproductoV_tb.getColumnModel().getColumn(5).setMinWidth(110);
            lsproductoV_tb.getColumnModel().getColumn(5).setMaxWidth(120);
            lsproductoV_tb.getColumnModel().getColumn(6).setMinWidth(130);
        }

        cotizar_bttn.setBackground(new java.awt.Color(255, 255, 255));
        cotizar_bttn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        cotizar_bttn.setForeground(new java.awt.Color(37, 60, 89));
        cotizar_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/quote.png"))); // NOI18N
        cotizar_bttn.setText("Cotizar");
        cotizar_bttn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        vaciarlista_bttn.setBackground(new java.awt.Color(255, 255, 255));
        vaciarlista_bttn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        vaciarlista_bttn.setForeground(new java.awt.Color(37, 60, 89));
        vaciarlista_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clean.png"))); // NOI18N
        vaciarlista_bttn.setText("Vaciar lista");
        vaciarlista_bttn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        quitarls_bttn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        quitarls_bttn.setForeground(new java.awt.Color(37, 60, 89));
        quitarls_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/quitItem.png"))); // NOI18N
        quitarls_bttn.setText("Quitar de la Lista");
        quitarls_bttn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cotizar_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vaciarlista_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quitarls_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vaciarlista_bttn)
                    .addComponent(cotizar_bttn)
                    .addComponent(quitarls_bttn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel27.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(37, 60, 89));
        jLabel27.setText("Fecha de la venta :");

        out_dateV_lb.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        out_dateV_lb.setForeground(new java.awt.Color(37, 60, 89));
        out_dateV_lb.setText("05/02/2023");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 60, 89));
        jLabel2.setText("Usuario :");

        out_usuario_lb.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        out_usuario_lb.setForeground(new java.awt.Color(37, 60, 89));
        out_usuario_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        out_usuario_lb.setText("Usuario 001");

        javax.swing.GroupLayout bgWhiteVenta_jpLayout = new javax.swing.GroupLayout(bgWhiteVenta_jp);
        bgWhiteVenta_jp.setLayout(bgWhiteVenta_jpLayout);
        bgWhiteVenta_jpLayout.setHorizontalGroup(
            bgWhiteVenta_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgWhiteVenta_jpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgWhiteVenta_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgWhiteVenta_jpLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(out_dateV_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(out_usuario_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        bgWhiteVenta_jpLayout.setVerticalGroup(
            bgWhiteVenta_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgWhiteVenta_jpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgWhiteVenta_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(out_dateV_lb)
                    .addComponent(jLabel2)
                    .addComponent(out_usuario_lb))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgWhiteVenta_jp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bgBlueVenta_jp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bgBlueVenta_jp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bgWhiteVenta_jp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgBlueVenta_jp;
    private javax.swing.JPanel bgWhiteVenta_jp;
    private javax.swing.JButton cancelarCobro_bttn;
    private javax.swing.JComboBox<String> clientes_jcbx;
    private javax.swing.JButton cobrar_bttn;
    private javax.swing.JButton cotizar_bttn;
    private javax.swing.JComboBox<String> descuento_jcbx;
    private javax.swing.JComboBox<String> frPago_jcbx;
    private javax.swing.JTextField in_efectivo_txf;
    private javax.swing.JTextField input_searchProduct_txf;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable lsProducto_tb;
    private javax.swing.JTable lsproductoV_tb;
    private javax.swing.JLabel out_cambio_lb;
    private javax.swing.JLabel out_dateV_lb;
    private javax.swing.JLabel out_folioVenta_lb;
    private javax.swing.JLabel out_pago_lb;
    private javax.swing.JLabel out_total_lb;
    private javax.swing.JLabel out_usuario_lb;
    private javax.swing.JButton quitarls_bttn;
    private javax.swing.JButton vaciarlista_bttn;
    // End of variables declaration//GEN-END:variables
}
