/**
 * Tema: 02 Registro Datos Personales
 * Conceptos: Registro Datos Personales
 * Autor: Emmlg
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lopez
 */
public class Registro_GUI extends javax.swing.JFrame {
    
    DefaultTableModel dtm=new DefaultTableModel();
    

    /**
     * Creates new form Registro_GUI
     */
    public Registro_GUI() {
        initComponents();
        
        
        String[] titleTable=new String[]{"CURP","RFC","Nombre","Tipo de Persona","Grado Estudio","puesto",
            "genero","estado","Nacionalidad","Edad","Razon socil","Empresa","Fecha N","Telefono","E-Mail","Sitio Web","Direccion"};
        dtm.setColumnIdentifiers(titleTable);
        datos_tb.setModel(dtm);
        
                

    } 

 // METODOS
    
    public void agregarDatos(){
        
        SimpleDateFormat dFormat=new SimpleDateFormat("dd-MM-yyyy");
       String date=dFormat.format(birth_jdate.getDate());

    
    dtm.addRow(new Object[]{
    curp_txf.getText(),rfc_txf.getText(),nombre_cbx.getSelectedItem().toString(),tPersona_jcbx.getSelectedItem(),gdoEstudio_cbx.getSelectedItem().toString(),
    puesto_cbx.getSelectedItem().toString(),genero_cbx.getSelectedItem().toString(),estado_cbx.getSelectedItem().toString(),
    nacionalidad_txf.getText(),edad_lb.getText(),razonSocial_txf.getText(),empresa_lb.getText(),date,
    phone_txf.getText(),eMail_txf.getText(),sitioWeb_lb.getText(),calle_cbx.getSelectedItem().toString()
    });
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background_jp = new javax.swing.JPanel();
        tpersona_lb = new javax.swing.JLabel();
        tPersona_jcbx = new javax.swing.JComboBox<>();
        datoPersonales_jp = new javax.swing.JPanel();
        curp_lb = new javax.swing.JLabel();
        curp_txf = new javax.swing.JTextField();
        rfc_lb = new javax.swing.JLabel();
        rfc_txf = new javax.swing.JTextField();
        nombre_lb = new javax.swing.JLabel();
        nombre_cbx = new javax.swing.JComboBox<>();
        apPaterno_lb = new javax.swing.JLabel();
        apPaterno_cbx = new javax.swing.JComboBox<>();
        apMaterno_lb = new javax.swing.JLabel();
        apMaterno_cbx = new javax.swing.JComboBox<>();
        puesto_lb = new javax.swing.JLabel();
        puesto_cbx = new javax.swing.JComboBox<>();
        gdoEstudio_lb = new javax.swing.JLabel();
        gdoEstudio_cbx = new javax.swing.JComboBox<>();
        naional_lb = new javax.swing.JLabel();
        nacionalidad_txf = new javax.swing.JTextField();
        genero_lb = new javax.swing.JLabel();
        genero_cbx = new javax.swing.JComboBox<>();
        estadoCivil_lb = new javax.swing.JLabel();
        estadoCivil_cbx = new javax.swing.JComboBox<>();
        edad_lb = new javax.swing.JLabel();
        Age_txf = new javax.swing.JTextField();
        rzsocial_lb = new javax.swing.JLabel();
        razonSocial_txf = new javax.swing.JTextField();
        birth_lb = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        phone_txf = new javax.swing.JTextField();
        email_lb = new javax.swing.JLabel();
        eMail_txf = new javax.swing.JTextField();
        sitioWeb_lb = new javax.swing.JLabel();
        webPage_txf = new javax.swing.JTextField();
        empresa_lb = new javax.swing.JLabel();
        company_txf = new javax.swing.JTextField();
        birth_jdate = new com.toedter.calendar.JDateChooser();
        option_jp = new javax.swing.JPanel();
        grabar_btt = new javax.swing.JButton();
        del_btt = new javax.swing.JButton();
        modificar_btt = new javax.swing.JButton();
        cancelar_btt = new javax.swing.JButton();
        salir_btt = new javax.swing.JButton();
        direccion_jp = new javax.swing.JPanel();
        calle_lb = new javax.swing.JLabel();
        calle_cbx = new javax.swing.JComboBox<>();
        colonia_lb = new javax.swing.JLabel();
        colonia_txf = new javax.swing.JComboBox<>();
        homenumber_lb = new javax.swing.JLabel();
        numeroHome_txf = new javax.swing.JTextField();
        municipio_lb = new javax.swing.JLabel();
        municipio_cbx = new javax.swing.JComboBox<>();
        estado_lb = new javax.swing.JLabel();
        estado_cbx = new javax.swing.JComboBox<>();
        cp_lb = new javax.swing.JLabel();
        cp_txf = new javax.swing.JTextField();
        contenido_jp = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datos_tb = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tpersona_lb.setText("Tipo de Persona");

        tPersona_jcbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Empleado", "Proveedor" }));

        datoPersonales_jp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos personales"));

        curp_lb.setText("CURP");

        rfc_lb.setText("RFC");

        nombre_lb.setText("Nombre");

        nombre_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- seleccionar --", "Emmanuel", "Jesus", "Moises", "Julio", "Juan", "Paola", " " }));

        apPaterno_lb.setText("Apellido Paterno");

        apPaterno_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- seleccionar --", "Sanches", "Perez", "Santos", "pinto", "Gomez", "Lara", "Aguilar", " " }));

        apMaterno_lb.setText("Apellido Materno");

        apMaterno_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- seleccionar --", "Gonzales", "Perez", "Pinto", "Lopez", "Sanchez", " " }));

        puesto_lb.setText("Puesto");

        puesto_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- seleccionar --", "Cajero", "Sin puesto" }));

        gdoEstudio_lb.setText("Gdo.Estudio");

        gdoEstudio_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- seleccionar --", "Licenciatura", "Preparatoria" }));

        naional_lb.setText("Nacionalidad");

        genero_lb.setText("Genero");

        genero_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- seleccionar --", "Masculino", "Femenino" }));

        estadoCivil_lb.setText("Estado Civil");

        estadoCivil_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- seleccionar --", "Casado", "Soltero", "Union libre" }));

        edad_lb.setText("Edad");

        rzsocial_lb.setText("Razón Social");

        birth_lb.setText("Fecha  de Nacimiento");

        jLabel14.setText("Teléfono");

        email_lb.setText("E-Mail");

        sitioWeb_lb.setText("Sitio Web");

        empresa_lb.setText("Empresa");

        javax.swing.GroupLayout datoPersonales_jpLayout = new javax.swing.GroupLayout(datoPersonales_jp);
        datoPersonales_jp.setLayout(datoPersonales_jpLayout);
        datoPersonales_jpLayout.setHorizontalGroup(
            datoPersonales_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datoPersonales_jpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datoPersonales_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datoPersonales_jpLayout.createSequentialGroup()
                        .addComponent(curp_lb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(curp_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rfc_lb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rfc_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre_lb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apPaterno_lb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apPaterno_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apMaterno_lb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apMaterno_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(puesto_lb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(puesto_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datoPersonales_jpLayout.createSequentialGroup()
                        .addGroup(datoPersonales_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, datoPersonales_jpLayout.createSequentialGroup()
                                .addComponent(birth_lb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(birth_jdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, datoPersonales_jpLayout.createSequentialGroup()
                                .addComponent(gdoEstudio_lb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gdoEstudio_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(naional_lb)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(datoPersonales_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datoPersonales_jpLayout.createSequentialGroup()
                                .addComponent(nacionalidad_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genero_lb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genero_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadoCivil_lb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadoCivil_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edad_lb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Age_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(datoPersonales_jpLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phone_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(email_lb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eMail_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sitioWeb_lb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(webPage_txf, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(datoPersonales_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datoPersonales_jpLayout.createSequentialGroup()
                                .addComponent(rzsocial_lb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(razonSocial_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(datoPersonales_jpLayout.createSequentialGroup()
                                .addComponent(empresa_lb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(company_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        datoPersonales_jpLayout.setVerticalGroup(
            datoPersonales_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datoPersonales_jpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datoPersonales_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curp_lb)
                    .addComponent(curp_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rfc_lb)
                    .addComponent(rfc_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre_lb)
                    .addComponent(nombre_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apPaterno_lb)
                    .addComponent(apPaterno_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apMaterno_lb)
                    .addComponent(apMaterno_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puesto_lb)
                    .addComponent(puesto_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(datoPersonales_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gdoEstudio_lb)
                    .addComponent(gdoEstudio_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(naional_lb)
                    .addComponent(nacionalidad_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genero_lb)
                    .addComponent(genero_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoCivil_lb)
                    .addComponent(estadoCivil_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edad_lb)
                    .addComponent(Age_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rzsocial_lb)
                    .addComponent(razonSocial_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(datoPersonales_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datoPersonales_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(birth_lb)
                        .addComponent(jLabel14)
                        .addComponent(phone_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(email_lb)
                        .addComponent(eMail_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sitioWeb_lb)
                        .addComponent(webPage_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(empresa_lb)
                        .addComponent(company_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(birth_jdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        option_jp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opciones"));

        grabar_btt.setText("Grabar");
        grabar_btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabar_bttActionPerformed(evt);
            }
        });

        del_btt.setText("Eliminar");

        modificar_btt.setText("Modificar");

        cancelar_btt.setText("Cancelar");

        salir_btt.setText("Salir");

        javax.swing.GroupLayout option_jpLayout = new javax.swing.GroupLayout(option_jp);
        option_jp.setLayout(option_jpLayout);
        option_jpLayout.setHorizontalGroup(
            option_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(option_jpLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(option_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(option_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cancelar_btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salir_btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(del_btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(grabar_btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(modificar_btt))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        option_jpLayout.setVerticalGroup(
            option_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(option_jpLayout.createSequentialGroup()
                .addComponent(grabar_btt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(del_btt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificar_btt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelar_btt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salir_btt))
        );

        direccion_jp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dirección"));

        calle_lb.setText("Calle");

        calle_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- seleccionar --", "1Av norte", "2Av Norte", "1AV sur", "3AV Sur", " " }));

        colonia_lb.setText("Colonia");

        colonia_txf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- seleccionar --", "Guadalupe", "El cedro", "Centro", "San miguel", " " }));

        homenumber_lb.setText("Número");

        municipio_lb.setText("Municipio");

        municipio_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- seleccionar --", "Margaritas", "Trinitaria", "Villa Flores", " ", " ", " " }));

        estado_lb.setText("Estado");

        estado_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- seleccionar --", "Chiapas", "Chihuahua", "Queretaro", "Colima", "Puebla", "Oaxaca", " " }));

        cp_lb.setText("Código Postal");

        javax.swing.GroupLayout direccion_jpLayout = new javax.swing.GroupLayout(direccion_jp);
        direccion_jp.setLayout(direccion_jpLayout);
        direccion_jpLayout.setHorizontalGroup(
            direccion_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(direccion_jpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calle_lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calle_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colonia_lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colonia_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homenumber_lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroHome_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(municipio_lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(municipio_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estado_lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estado_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cp_lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cp_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        direccion_jpLayout.setVerticalGroup(
            direccion_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(direccion_jpLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(direccion_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calle_lb)
                    .addComponent(calle_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colonia_lb)
                    .addComponent(colonia_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homenumber_lb)
                    .addComponent(numeroHome_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(municipio_lb)
                    .addComponent(municipio_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estado_lb)
                    .addComponent(estado_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cp_lb)
                    .addComponent(cp_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contenido_jp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Contenido"));

        datos_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(datos_tb);

        javax.swing.GroupLayout contenido_jpLayout = new javax.swing.GroupLayout(contenido_jp);
        contenido_jp.setLayout(contenido_jpLayout);
        contenido_jpLayout.setHorizontalGroup(
            contenido_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenido_jpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        contenido_jpLayout.setVerticalGroup(
            contenido_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenido_jpLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout background_jpLayout = new javax.swing.GroupLayout(background_jp);
        background_jp.setLayout(background_jpLayout);
        background_jpLayout.setHorizontalGroup(
            background_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_jpLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tpersona_lb)
                .addGap(5, 5, 5)
                .addComponent(tPersona_jcbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(background_jpLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(background_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datoPersonales_jp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(direccion_jp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(option_jp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(background_jpLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(contenido_jp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        background_jpLayout.setVerticalGroup(
            background_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_jpLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(background_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background_jpLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(tpersona_lb))
                    .addComponent(tPersona_jcbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(background_jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background_jpLayout.createSequentialGroup()
                        .addComponent(datoPersonales_jp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(direccion_jp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(background_jpLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(option_jp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61)))
                .addGap(7, 7, 7)
                .addComponent(contenido_jp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_jp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_jp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void grabar_bttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabar_bttActionPerformed
  
        agregarDatos();
    }//GEN-LAST:event_grabar_bttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age_txf;
    private javax.swing.JComboBox<String> apMaterno_cbx;
    private javax.swing.JLabel apMaterno_lb;
    private javax.swing.JComboBox<String> apPaterno_cbx;
    private javax.swing.JLabel apPaterno_lb;
    private javax.swing.JPanel background_jp;
    private com.toedter.calendar.JDateChooser birth_jdate;
    private javax.swing.JLabel birth_lb;
    private javax.swing.JComboBox<String> calle_cbx;
    private javax.swing.JLabel calle_lb;
    private javax.swing.JButton cancelar_btt;
    private javax.swing.JLabel colonia_lb;
    private javax.swing.JComboBox<String> colonia_txf;
    private javax.swing.JTextField company_txf;
    private javax.swing.JPanel contenido_jp;
    private javax.swing.JLabel cp_lb;
    private javax.swing.JTextField cp_txf;
    private javax.swing.JLabel curp_lb;
    private javax.swing.JTextField curp_txf;
    private javax.swing.JPanel datoPersonales_jp;
    private javax.swing.JTable datos_tb;
    private javax.swing.JButton del_btt;
    private javax.swing.JPanel direccion_jp;
    private javax.swing.JTextField eMail_txf;
    private javax.swing.JLabel edad_lb;
    private javax.swing.JLabel email_lb;
    private javax.swing.JLabel empresa_lb;
    private javax.swing.JComboBox<String> estadoCivil_cbx;
    private javax.swing.JLabel estadoCivil_lb;
    private javax.swing.JComboBox<String> estado_cbx;
    private javax.swing.JLabel estado_lb;
    private javax.swing.JComboBox<String> gdoEstudio_cbx;
    private javax.swing.JLabel gdoEstudio_lb;
    private javax.swing.JComboBox<String> genero_cbx;
    private javax.swing.JLabel genero_lb;
    private javax.swing.JButton grabar_btt;
    private javax.swing.JLabel homenumber_lb;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar_btt;
    private javax.swing.JComboBox<String> municipio_cbx;
    private javax.swing.JLabel municipio_lb;
    private javax.swing.JTextField nacionalidad_txf;
    private javax.swing.JLabel naional_lb;
    private javax.swing.JComboBox<String> nombre_cbx;
    private javax.swing.JLabel nombre_lb;
    private javax.swing.JTextField numeroHome_txf;
    private javax.swing.JPanel option_jp;
    private javax.swing.JTextField phone_txf;
    private javax.swing.JComboBox<String> puesto_cbx;
    private javax.swing.JLabel puesto_lb;
    private javax.swing.JTextField razonSocial_txf;
    private javax.swing.JLabel rfc_lb;
    private javax.swing.JTextField rfc_txf;
    private javax.swing.JLabel rzsocial_lb;
    private javax.swing.JButton salir_btt;
    private javax.swing.JLabel sitioWeb_lb;
    private javax.swing.JComboBox<String> tPersona_jcbx;
    private javax.swing.JLabel tpersona_lb;
    private javax.swing.JTextField webPage_txf;
    // End of variables declaration//GEN-END:variables
}
